name: taylor-swift-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - matplotlib
  - seaborn
  - nltk
  - notebook
  - ipykernel
  - pip
  - pip:
    - jupyter
    - notebook
    - ipywidgets
